### ISSUE TITLE
Deploying to clusters

### ISSUE THREAD

**Issue by Bilge** [thephpleague/shunt#17]
Can you really only define a single host per name? How are you expected to deploy to an entire live cluster without being able to define an array of target hosts?

**Comment by toopay** [comment]
Hey @Bilge This library wasn't built for fancy distributed system in mind, so yeah you'll need to rigoriously setup all cluster member hosts and orchestrate the deployment strategy yourself.

**Comment by Bilge** [comment]
Are you trying to say it's shit by design? Maybe you should add that to the readme.

**Comment by toopay** [comment]
@Bilge Well, thats depend. 

If you're trying to use this library to orchestrate deployment for some Erlang or Scala software, then it could be the case. But for common PHP project (please remember, this is PHP library), then its sufficient.

**Comment by Bilge** [comment]
That's probably the most backwards thing I've read all week. Do you earnestly believe there are more full scale Erlang/Scala deployments in production than PHP or is there some more contrived reason for your bigotry?

**Comment by toopay** [comment]
> Do you earnestly believe there are more full scale Erlang/Scala deployments in production than PHP

Back to your original issue, thats to say, if i have 3 node as member in one cluster, i would set each name for each host/node. I was not put further consideration about how this task runner allowing developer to mapping one name to an array of hosts/node and provides a fancy mechanism to orchestrate the deployment process in that cluster - because most PHP project i've ever worked doesn't built that way. 

So yes I do believe. Its not that i use PHP as insult here, but the fact that PHP doesn't have complexity when dealing with distribution world (eg : its okay to put "sorry we're down" on PHP app since there is no hot-swap code support - comparing to how i could do it on Erlang) - make me simplify some aspect, and your case is one i didn't need in the time i wrote this "simple" library. Is that mean this libray "shit by design" as you'd previously said? For me - and my PHP apps that powered by this library - it wasn't. But it's probably is, for my Erlang apps.

Thats, if you want a full disclosure. 

If you have time to patching this library to allow above case, i will gladly review it and as long as it doesn't break my running apps i may could live with it.  Otherwise, stop posting useless comment.
